### ISSUE TITLE
Investigate Superset DASHBOARD_RBAC

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-oars#27]
Per a removed TODO in the code:

https://github.com/openedx/tutor-contrib-oars/blob/0019a992e333a5871e056c7f4968e6088aae5474/tutoroars/templates/oars/apps/pythonpath/superset-dashboard.py#L66

    # TODO: Enable feature flag DASHBOARD_RBAC, and set dashboard.roles = ["Open edX"]
    # Consider finishing https://github.com/opus-42/superset-api-client/pull/31

This relates generally to our authorization story and making sure users only see what they're supposed to. @pomegranited probably has more relevant context.

**Comment by mariajgrimaldi** [comment]
Hi there! Can you shed some light on this issue so we can help @pomegranited? Thanks!

**Comment by pomegranited** [comment]
@mariajgrimaldi @bmtcril I think that enabling `DASHBOARD_RBAC` lets us set up roles that are allowed to access specific Dashboards (and their charts and datasets), so that different roles can see different Dashboards depending on what they care about.  E.g., System Admins could see system-monitoring dashboards, Program Admins can see program-level dashboards, etc.

However [the docs](https://superset.apache.org/docs/creating-charts-dashboards/creating-your-first-dashboard/#manage-access-to-dashboards) say that if `DASHBOARD_RBAC ` is enabled:

> Granting a role access to a dashboard will bypass dataset level checks.

So we need to make sure that enabling `DASHBOARD_RBAC` doesn't bypass our [Row Level Security](https://superset.apache.org/docs/security#row-level-security), which currently is how we restrict access to data to course staff.

https://github.com/opus-42/superset-api-client/pull/31 is about ensuring that we can pass a list of roles when importing a Dashboard into the Superset API.

**Comment by Ian2012** [comment]
@bmtcril What if we define a Jinja template that fetches current user permission from the MySQL DB and uses it in the dashboard queries to filter the data based on the current user? This would allow us to enable `DASHBOARD_RBAC` for different roles, and keep the amount of dashboard static (not using the Cairn approach).

cc @pomegranited @mariajgrimaldi any thoughts?

**Comment by bmtcril** [comment]
@Ian2012 I definitely don't want to tie us directly to the MySQL db in any way. I think we can refresh permissions periodically using SSO and still keep the `DASHBOARD_RBAC`?

**Comment by Ian2012** [comment]
@bmtcril Can this be closed or is anything missing?

**Comment by bmtcril** [comment]
I think this is in a decent place, if there are bugs we can open a new issue.
